trigger: none
pr: none

jobs:
  - job: "General"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'clean publishAllPublicationsToMavenRepository'
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: $(sonatype_username)
          ORG_GRADLE_PROJECT_sonatypePassword: $(sonatype_password)
          ORG_GRADLE_PROJECT_signingKey: $(secret_key)
          ORG_GRADLE_PROJECT_signingPassword: $(signing_password)

    pool:
      vmImage: 'ubuntu-latest'

  - job: "Mac"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'clean publishIosArm32PublicationToMavenRepository publishIosArm64PublicationToMavenRepository publishIosX64PublicationToMavenRepository publishMacosX64PublicationToMavenRepository publishWatchosArm32PublicationToMavenRepository publishWatchosArm64PublicationToMavenRepository publishWatchosX86PublicationToMavenRepository publishTvosArm64PublicationToMavenRepository publishTvosX64PublicationToMavenRepository'
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: $(sonatype_username)
          ORG_GRADLE_PROJECT_sonatypePassword: $(sonatype_password)
          ORG_GRADLE_PROJECT_signingKey: $(secret_key)
          ORG_GRADLE_PROJECT_signingPassword: $(signing_password)

    pool:
      vmImage: 'macos-latest'

  - job: "Windows"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'clean publishMingwX64PublicationToMavenRepository publishMingwX86PublicationToMavenRepository'
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: $(sonatype_username)
          ORG_GRADLE_PROJECT_sonatypePassword: $(sonatype_password)
          ORG_GRADLE_PROJECT_signingKey: $(secret_key)
          ORG_GRADLE_PROJECT_signingPassword: $(signing_password)

    pool:
      vmImage: 'windows-latest'
